spring.application.name=saitama-school-advisor
server.port=8080
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/school_advisor}
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=otsubo0516
spring.datasource.hikari.connection-init-sql=SET client_encoding TO 'UTF8'
spring.sql.init.mode=${DB_INIT_MODE:never}
